---
provisioner:
  name: chef_zero
  data_bags_path: <%= ENV['CHEF_DATA_BAGS_PATH'] %>
  encrypted_data_bag_secret_key_path: <%= ENV['CHEF_DATA_BAG_SECRET_KEY'] %>
  require_chef_omnibus: 12.13.37

driver:
  name: ec2
  security_group_ids:
    - sg-9ca1a7e6
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID']%>
  availability_zone: <%= ENV['AWS_DEFAULT_REGION'] %>a
  vpc_mode: true
  vpc: vpc-4251db24
  subnet_id: subnet-8d18e3c5
  associate_public_ip: true

platforms:
  - name: CentOS_69
    driver:
      image_id: ami-207b8058
      instance_type: t2.medium
      associate_public_ip: true
      iam_profile_name: main_infra
      block_device_mappings:
      - device_name: /dev/sda1
        ebs:
          volume_size: 8
          delete_on_termination: true
      tags:
        Name: maduro-testbooks-tk
        Product: maduro.nfernal
        ChargeCode: testbook

transport:
  name: ssh
  connection_timeout: 15
  connection_retries: 30
  ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
  username: centos

verifier:
  name: inspec
  inspec_tests:
        - test/integration/default

suites:
  - name: default
    run_list:
      - recipe[testbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
