source 'https://rubygems.org'

gem 'kitchen'
gem 'test-kitchen'
gem 'berkshelf'
gem 'chef'
gem 'chefspec'
gem 'inspec'
gem 'serverspec'
gem 'rubocop'
gem 'rake'
gem 'kitchen-docker'
gem 'kitchen-dokken'
gem 'kitchen-ec2'
gem 'kitchen-inspec'
gem 'kitchen-vagrant'
