version: 2
jobs:
  build:
    docker:
      - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
        environment:
          AWS_DEFAULT_OUTPUT: json
          AWS_DEFAULT_REGION: us-west-2
          AWS_SSH_KEY_ID: circle-rsa
          AWS_SSH_KEY: /root/.ssh/id_rsa
          CIRCLE_WORKING_DIRECTORY: ~/chef-repo/cookbooks
    steps:
      - checkout
      - run:
          name: Download Data Bags
          working_directory: ~/chef-repo
          command: knife download data_bags
      - run:
          name: Moving the project directory
          working_directory: /root
          command: mv project ~/chef-repo/cookbooks
      - run:
          name: Kitchen List
          working_directory: ~/chef-repo/cookbooks/project
          command: chef exec bundle exec kitchen test
