version: 2
jobs:
  build:
    docker:
      - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
        environment:
          AWS_DEFAULT_OUTPUT: json
          AWS_DEFAULT_REGION: us-west-2
          AWS_SSH_KEY_ID: circle_rsa
          AWS_SSH_KEY: /root/.ssh/circle_rsa
    steps:
      - checkout
      - run:
          name: Download Data Bags
          working_directory: ~/chef-repo
          command: knife download data_bags
      - run:
          name: Integration Tests
          command: env


